---
- name: Add pi host
  hosts: localhost
  tasks:
    - add_host:
        name: "{{ip_address}}"
        groups: pi

- name: provision
  remote_user: root
  hosts: pi
  # Do not gather facts here because initially python2, an Ansible dependency is not installed
  gather_facts: false
  pre_tasks:
    - name: 'Install python2'
      raw: pacman -Sy --noconfirm --needed python2 && ln -sf /usr/bin/python2 /usr/bin/python
    - name: Gather facts
      setup: # Now gather facts: http://stackoverflow.com/a/31060268/626911
  roles:
    - hostname
    - timezone
    - user
    - utils
    - wifi
    - spi
    - node
    - { role: relay-rest-api, tags: ['relay-rest-api'] }